### ISSUE TITLE
Missing changes for 0.03

### ISSUE THREAD

**Issue by dolmen** [naturalist/pod-markdown-github#5]
Version 0.03 has been released on CPAN, but its [Changes](https://metacpan.org/source/MINIMAL/Pod-Markdown-Github-0.03/Changes) files lack information about what changed since 0.02.

**Comment by sgnix** [comment]
There were no code changes. Changes file fixed in https://github.com/naturalist/pod-markdown-github/commit/aeeecbd78425b58f9f32f4d5d3c0513b64ed483e
