### ISSUE TITLE
Testsuite do not pass with Pod::Markdown 2.002

### ISSUE THREAD

**Issue by dolmen** [naturalist/pod-markdown-github#6]
... but installing Pod::Markdown 3.005 fixed the issue.

So the dependency on Pod::Markdown should probably be upgraded in `cpanfile` and/or `dist.ini`...

**Comment by sgnix** [comment]
Fixed in https://github.com/naturalist/pod-markdown-github/commit/802de46cf9267885efcb7376c98985513ba27a99
