### ISSUE TITLE
Test::Pod dep is misnamed for cpanfile

### ISSUE THREAD

**Issue by SineSwiper** [naturalist/pod-markdown-github#7]
The cpanfile test section shows:

```# for test
on test => sub {
    requires 'Test-Pod', '0.04';
    requires 'Test::More', '1.001006';
};
```

However, it shouldn't be called 'Test-Pod', but 'Test::Pod'.  This confuses cpanm when using `--installdeps`.

**Comment by sgnix** [comment]
Fixed in https://github.com/naturalist/pod-markdown-github/commit/df56da48cc7642ee2e25d1b1a0656563f0eb09be
