### ISSUE TITLE
pod2github is misattributed

### ISSUE THREAD

**Issue by karenetheridge** [naturalist/pod-markdown-github#9]
The source for https://metacpan.org/source/MINIMAL/Pod-Markdown-Github-0.03/bin/pod2github says the file comes from the Pod-Markdown distribution. This is false -- it actually comes from your distribution, Pod-Markdown-Github. While the author and copyright information should indicate it was *based on* Pod-Markdown, its source is actually different and uses Pod::Markdown::Github instead of Pod::Markdown.

(The $VERSION in this file is also wrong, as it was copied from the Pod-Markdown distribution as well. I would suggest adding Pod-Markdown-Github's $VERSION instead.)

**Comment by sgnix** [comment]
Noted. Will remove the copy-pasta this week.

**Comment by sgnix** [comment]
Fixed in https://github.com/naturalist/pod-markdown-github/commit/596c620e76533f3cadb1651d2d40b572554a8bdb

**Comment by karenetheridge** [comment]
thanks! 👍💃🏼🐸
